<a href="https://colab.research.google.com/github/Avinash-yadav220/pytorch-tut/blob/main/tensor_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TENSOR MATH OPERATIONS**


*   Add, Subtract, Multiply, Divide, Remainders, Exponents
*   Shorthand and uh, Longhand
*   Reassignment



In [1]:
import torch
import numpy as np

In [2]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [3]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [4]:
# Addition Longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [5]:
# Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [6]:
# Sub Function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [7]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [8]:
# Mul longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [9]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [10]:
# Div Longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [11]:
# Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [12]:
# Remainder longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [13]:
# Exponents / power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [14]:
# Another way to write longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [15]:
# Reassignment_
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [16]:
tensor_a

tensor([1, 2, 3, 4])

In [17]:
#tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [18]:
tensor_a

tensor([ 6,  8, 10, 12])

**TENSOR MATH OPERATIONS**


*   Add, Subtract, Multiply, Divide, Remainders, Exponents
*   Shorthand and uh, Longhand
*   Reassignment



In [19]:
import torch
import numpy as np

In [20]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [21]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [22]:
# Addition Longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [23]:
# Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [24]:
# Sub Function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [25]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [26]:
# Mul longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [27]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [28]:
# Div Longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [29]:
# Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [30]:
# Remainder longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [31]:
# Exponents / power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [32]:
# Another way to write longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [33]:
# Reassignment_
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [34]:
tensor_a

tensor([1, 2, 3, 4])

In [35]:
#tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [36]:
tensor_a

tensor([ 6,  8, 10, 12])

**TENSOR MATH OPERATIONS**


*   Add, Subtract, Multiply, Divide, Remainders, Exponents
*   Shorthand and uh, Longhand
*   Reassignment



In [37]:
import torch
import numpy as np

In [38]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [39]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [40]:
# Addition Longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [41]:
# Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [42]:
# Sub Function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [43]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [44]:
# Mul longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [45]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [46]:
# Div Longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [47]:
# Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [48]:
# Remainder longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [49]:
# Exponents / power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [50]:
# Another way to write longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [51]:
# Reassignment_
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [52]:
tensor_a

tensor([1, 2, 3, 4])

In [53]:
#tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [54]:
tensor_a

tensor([ 6,  8, 10, 12])

**TENSOR MATH OPERATIONS**


*   Add, Subtract, Multiply, Divide, Remainders, Exponents
*   Shorthand and uh, Longhand
*   Reassignment



In [55]:
import torch
import numpy as np

In [56]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [57]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [58]:
# Addition Longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [59]:
# Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [60]:
# Sub Function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [61]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [62]:
# Mul longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [63]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [64]:
# Div Longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [65]:
# Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [66]:
# Remainder longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [67]:
# Exponents / power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [68]:
# Another way to write longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [69]:
# Reassignment_
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [70]:
tensor_a

tensor([1, 2, 3, 4])

In [71]:
#tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [72]:
tensor_a

tensor([ 6,  8, 10, 12])