<a href="https://colab.research.google.com/github/Avinash-yadav220/pytorch-tut/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **TENSORS**

*   A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.

*   Similar To Numpy Arrays, but full of fun things that make them work better on GPU's (vs regular CPU's).

*  default data type of float32.

* More suitable for deep learning than a numpy array.







In [8]:
import torch
import numpy as np

# **LISTS**


In [2]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list


[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

# **NUMPY ARRAYS**

In [3]:
np1 = np.random.rand(3,4)
np1


array([[0.34254444, 0.09636049, 0.94637644, 0.9279332 ],
       [0.63941823, 0.74527246, 0.66801883, 0.66111236],
       [0.53548088, 0.81116933, 0.45812475, 0.46300175]])

In [4]:
np1.dtype


dtype('float64')

# **TENSORS**

In [5]:
tensor_2d = torch.randn(3,4)
tensor_2d
#tensor_2d.dtype

tensor([[-1.4930, -0.1263, -0.4642, -0.1899],
        [ 0.0075,  1.5754, -0.3873, -0.2748],
        [ 0.5648, -0.0257, -0.9939,  0.6029]])

In [6]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.3425, 0.0964, 0.9464, 0.9279],
        [0.6394, 0.7453, 0.6680, 0.6611],
        [0.5355, 0.8112, 0.4581, 0.4630]], dtype=torch.float64)